// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ76G-kTWS1iOFvfk0-OK2qY5iR1Dyj3A',
    appId: '1:615687440592:web:7f71ac3c67ee1d1d5436d5',
    messagingSenderId: '615687440592',
    projectId: 'mic-backoffice',
    authDomain: 'mic-backoffice.firebaseapp.com',
    storageBucket: 'mic-backoffice.firebasestorage.app',
    measurementId: 'G-YJ53DCP5EQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_4G2pbLYXy0veesp83yT-0UCTZ0VC-o8',
    appId: '1:615687440592:android:b1df66e246c8c78d5436d5',
    messagingSenderId: '615687440592',
    projectId: 'mic-backoffice',
    storageBucket: 'mic-backoffice.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6MXTlBT_VuMM8sMWuH_Id0sJ6Pf5qopA',
    appId: '1:615687440592:ios:3ce19e6691a78fb95436d5',
    messagingSenderId: '615687440592',
    projectId: 'mic-backoffice',
    storageBucket: 'mic-backoffice.firebasestorage.app',
    iosBundleId: 'com.example.micBackoffice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6MXTlBT_VuMM8sMWuH_Id0sJ6Pf5qopA',
    appId: '1:615687440592:ios:3ce19e6691a78fb95436d5',
    messagingSenderId: '615687440592',
    projectId: 'mic-backoffice',
    storageBucket: 'mic-backoffice.firebasestorage.app',
    iosBundleId: 'com.example.micBackoffice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZ76G-kTWS1iOFvfk0-OK2qY5iR1Dyj3A',
    appId: '1:615687440592:web:1cf676c94e7020f35436d5',
    messagingSenderId: '615687440592',
    projectId: 'mic-backoffice',
    authDomain: 'mic-backoffice.firebaseapp.com',
    storageBucket: 'mic-backoffice.firebasestorage.app',
    measurementId: 'G-QM2Y014CQ6',
  );
}
