name: Build Flutter Windows (Portable)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v5

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Get dependencies
        run: flutter pub get

      - name: Build Windows release
        run: flutter build windows --release

      - name: Upload portable app
        uses: actions/upload-artifact@v6
        with:
          name: windows-portable
          path: build/windows/x64/runner/Release/
